### ISSUE TITLE
problem install into existing project

### ISSUE THREAD

**Issue by Zacknero** [nestjs/ng-universal#156]
## Bug Report
problem install into existing project

## Current behavior
I have an existing project (Angular 8.x.x), when I try to install NestJS I have error problems when typing the name of the app.
My steps are:
1) I open the project folder
2) From the terminal, type the command "ng add @ nestjs / ng-universal"
3) Packages are installed
4) It asks me the name of the application where I type the exact name and it signals me this error:
Cannot read property 'kind' of undefined

## Input Code
ng add @ nestjs / ng-universal

## Environment
Angular 8

<pre><code>
Nest version: 6.8.0
Nest Universal 2.0.1
 
For Tooling issues:
- Node version: 10.16.0
- npm 6.9.0
- Platform:  Windows

**Comment by Zacknero** [comment]
@joeyslack your solution don't work, you can see my example project
[image](https://ibb.co/dt3YKxB)

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by Zacknero** [comment]
My step first is
1) npm i -g @nestjs/cli
2) nest new folder-name
3) cd folder-name
4) npm run start
5) Error (40)
[Error Console Log](https://ibb.co/d6b1BzY)

**Comment by krunalm1992** [comment]
I got same error while using angular cli version 8.1.3. Just updated my angular cli to version 8.3.24 and it works as expected.

**Comment by kamilmysliwiec** [comment]
This should be fixed with Angular 9

**Comment by Zacknero** [comment]
> This should be fixed with Angular 9

Ok, if we are on oldest version this isn't solved!!

[https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.boingboing.net%2Fwp-content%2Fuploads%2F2018%2F08%2FCF-ME2-XIAAOb-3.png&f=1&nofb=1](url)

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the `@angular/universal` repository. `@nestjs/ng-universal` is now just a wrapper on `@nguniversal/express-engine` which performs several minor modifications and nothing else.
